# Generated by Django 5.2.5 on 2025-10-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Product Name')),
                ('description', models.TextField(verbose_name='Product Description')),
                ('price', models.FloatField(verbose_name='Product Price')),
                ('price_type', models.CharField(choices=[('F', 'Fixed'), ('N', 'Negotiable')], max_length=1, verbose_name='Price Type [Negotiable/Fixed]')),
            ],
        ),
    ]
